import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState } from "react";
import { Button } from "~/component/button";
import { type Image as ImageType } from "openai/resources/images.mjs";

import { api } from "~/utils/api";
import Image from "next/image";

export default function Generate() {
  const [form, setForm] = useState({
    prompt: "",
  });

  const [imageData, setImageData] = useState<string>("");

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data, variables, context) {
      console.log(data);
      setImageData(data.imageUrl);
    },
  });

  function submitForm(e: React.FormEvent) {
    e.preventDefault();
    generateIcon.mutate({
      prompt: form.prompt,
    });
    setForm({
      prompt: "",
    });
  }

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm({
        ...form,
        [key]: e.target.value,
      });
    };
  }

  // function getSrc(b64_json: string): string {
  //   return `data:image/png;base64,${b64_json}`;
  // }

  const session = useSession();
  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Generate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-full flex-wrap items-center justify-center">
        <div className="flex flex-col gap-5">
          {!isLoggedIn && (
            <Button
              onClick={() => {
                signIn().catch(console.error);
              }}
            >
              Login
            </Button>
          )}

          {isLoggedIn && (
            <Button
              onClick={() => {
                signOut().catch(console.error);
              }}
            >
              Logout
            </Button>
          )}

          {session.data?.user.name}

          <form onSubmit={(e) => submitForm(e)} className="h-fit">
            <div className="flex flex-col gap-5">
              <label>Prompt</label>
              <input type="text" onChange={updateForm("prompt")} />
              <Button>Submit</Button>
            </div>
          </form>

          <div className="flex w-full flex-col items-center gap-2">
            {imageData && (
              <Image
                src={imageData}
                alt="The image that was generated by your prompt"
                width="512"
                height="512"
              />
            )}

            {/* {imageData.map((image, index) => {
              return (
                <Image
                  src={}
                  key={index + Math.random() * 1000}
                  alt="The image that was generated by your prompt"
                  width="512"
                  height="512"
                />
              );
            })} */}
          </div>
        </div>
      </div>
    </>
  );
}
