import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState } from "react";
import { Button } from "~/component/button";

import { api } from "~/utils/api";

export default function Generate() {
  const [form, setForm] = useState({
    prompt: "",
  });
  //   const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data, variables, context) {
      console.log(data.message);
    },
  });

  function submitForm(e: React.FormEvent) {
    e.preventDefault();
    generateIcon.mutate({
      prompt: form.prompt,
    });
  }

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm({
        ...form,
        [key]: e.target.value,
      });
    };
  }

  const session = useSession();
  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Generate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-full flex-wrap items-center justify-center">
        <div className="flex flex-col gap-5">
          {!isLoggedIn && (
            <Button
              onClick={() => {
                signIn().catch(console.error);
              }}
            >
              Login
            </Button>
          )}

          {isLoggedIn && (
            <Button
              onClick={() => {
                signOut().catch(console.error);
              }}
            >
              Logout
            </Button>
          )}

          {session.data?.user.name}

          <form onSubmit={(e) => submitForm(e)} className="h-fit">
            <div className="flex flex-col gap-5">
              <label>Prompt</label>
              <input type="text" onChange={updateForm("prompt")} />
              <Button>Submit</Button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
