import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/component/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="grid grid-cols-1 gap-10 px-8 pt-12 md:grid-cols-2 md:pt-24">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">
          Generate avatars with a click of the button
        </h1>
        <p className="text-2xl">
          Use AI to generate avatars instead of paying a designer and waiting
          them
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generate your avatars
        </PrimaryLinkButton>
      </div>

      <div className="order-first flex justify-center sm:order-none">
        <Image
          src="/banner.png"
          alt="a bunch of good looking avatars"
          width="700"
          height="400"
        />
      </div>
    </section>
  );
}

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Avatar Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
}
